version: '3.8'

services:
  # PostgreSQL databáze (stejná jako Railway)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend aplikace
  backend:
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      DATABASE_URL: 'postgresql://postgres:password@postgres:5432/railway'
      JWT_SECRET: 'local-development-secret-key'
      NODE_ENV: 'production'
      PORT: '3000'
      HOST: '0.0.0.0'
    ports:
      - '3000:3000'
      - '3001:3001'
    depends_on:
      - postgres
    volumes:
      # Pro live reload během vývoje
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
